name: 'Build c++ project'
description: 'Build c++ project with help cmake'
inputs:
  submodule_update:
    description: 'Git submodule update'
    required: false
    default: 'OFF'
  cmake_args:
    description: 'Cmake args (example -D<ARG1>=value;-D<ARG1>=value)'
    required: false
    default: ''
  googletests_on:
    description: 'Turn on google tests'
    required: false
    default: 'OFF'
  config:
    description: 'For multi-configuration tools, choose configuration <Release or Debug>'
    required: false
    default: 'Release'
runs:
  using: 'node12'
  main: 'index.js'